---
- hosts: 172.31.28.23
  become: yes
  tasks:
  - name: install git 
    apt: 
      name: git
      state: present
    register: myresult
    debug: 
       msg: "{{myresult}}"
    when: myresult.stderr !==" "

  - name: install git 
    apt: 
      name: tree
      state: present
    register: myresult  
    debug: 
       msg: "{{myresult}}"
    when: myresult.stderr ==" "
