---
- hosts: 172.31.28.23
  become: yes
  tasks:
  - name: install git 
    yum: 
      name: git 
      state: present
    tags: mygit  
    
  - name: install tree
    yum: 
      name: tree
      state: present
    tags: mytree  
    
  - name: install wget
    yum: 
      name: wget
      state: present
    tags: mywget    
